const fs = require('fs');
const path = require('path');

const localesDir = 'c:\\Users\\Ömer\\.gemini\\antigravity\\scratch\\my-first-react-site\\public\\locales';

const homeTranslations = {
    tr: {
        "home": {
            "hero_badge": "Türkiye'nin Dijital Lojistik Operatörü",
            "hero_title": "Yükünüzü Geleceğe Taşıyın",
            "hero_desc": "Onlarca doğrulanmış lojistik firmasından anında teklif alın. Deniz, kara ve havayolu çözümleriyle işinizi büyütün.",
            "hero_btn_explore": "Pazaryerini Keşfet",
            "hero_btn_post": "Hemen İlan Ver",
            "stats_total_ads": "Toplam İlan",
            "stats_active_ads": "Aktif İlan",
            "stats_bids": "Teklif Sayısı",
            "stats_ports": "Global Liman",
            "how_it_works_title": "Sistem Nasıl İşler?",
            "how_it_works_desc": "Karmaşık lojistik süreçlerini basitleştirdik",
            "step1_title": "Yükünüzü Tanımlayın",
            "step1_desc": "İhtiyacınızı detaylandırın. 2 dakika içinde ilanınız yayına alınsın.",
            "step2_title": "Teklifleri Karşılaştırın",
            "step2_desc": "Global firmalardan gelen şeffaf teklifleri değerlendirin.",
            "step3_title": "Süreci Yönetin",
            "step3_desc": "Anlaşmayı onaylayın ve yükünüzü varış noktasına kadar izleyin.",
            "why_title": "Neden Pruva?",
            "why_desc": "Profesyonel operasyonel mükemmellik",
            "feature1_title": "Hız ve Verimlilik",
            "feature1_desc": "Teklif alma süreçlerini %80 hızlandırarak zaman tasarrufu sağlayın.",
            "feature2_title": "Tam Güvenlik",
            "feature2_desc": "Doğrulanmış şirket profilleri ve şeffaf değerlendirme sistemi.",
            "feature3_title": "Anlık İzlenebilirlik",
            "feature3_desc": "Tüm aşamaları panelinizden adım adım takip edin.",
            "feature4_title": "Küresel Erişim",
            "feature4_desc": "Dünya çapında liman ve stratejik nokta ağı.",
            "feature5_title": "Kesintisiz İletişim",
            "feature5_desc": "Gelişmiş mesajlaşma altyapısı ile doğrudan koordinasyon.",
            "feature6_title": "Veri Analitiği",
            "feature6_desc": "Lojistik maliyetlerinizi analiz edin ve optimize edin.",
            "modes_title": "Lojistik Çözümleri",
            "modes_desc": "Her yük için özelleştirilmiş taşıma modları",
            "mode1_title": "Deniz Yolu",
            "mode1_desc": "FCL/LCL, Konteyner ve Proje Kargo çözümleri.",
            "mode1_badge": "Global Limanlar",
            "mode2_title": "Kara Yolu",
            "mode2_desc": "FTL/LTL ve Komple Tır taşımacılığı.",
            "mode2_badge": "Tüm Avrupa",
            "mode3_title": "Hava Yolu",
            "mode3_desc": "Express ve Standart havayolu kargo.",
            "mode3_badge": "En Hızlı Seçenek",
            "eco_title": "Pruva Ekosistemi",
            "eco_desc": "Sadece bir pazaryeri değil, lojistik çözüm ortağınız",
            "academy_badge": "Eğitim Portalı",
            "academy_title": "Pruva Akademi",
            "academy_desc": "16 modülden oluşan kapsamlı müfredatımızla lojistik dünyasında uzmanlaşın. Freight forwarder operasyonlarından gümrük süreçlerine kadar her şey burada.",
            "academy_f1": "16 Kapsamlı Modül",
            "academy_f2": "Profesyonel Sözlük & Terimler",
            "academy_f3": "İnteraktif Hesaplama Araçları",
            "academy_btn": "Keşfetmeye Başla",
            "ai_badge": "Yapay Zeka",
            "ai_title": "Pruva AI",
            "ai_desc": "Şirket mailinize entegre, teklifleri otomatik analiz eden ve sizin yerinize en iyi fiyatı pazarlık eden akıllı asistan.",
            "ai_status": "Pricing Modülü Aktif",
            "ai_f1": "Otomatik Mail Tarama",
            "ai_f2": "Akıllı Teklif Analizi",
            "ai_f3": "Otomatik Fiyat Pazarlığı",
            "ai_btn": "Şimdi Keşfet"
        }
    },
    en: {
        "home": {
            "hero_badge": "Turkey's Digital Logistics Operator",
            "hero_title": "Carry Your Cargo to the Future",
            "hero_desc": "Get instant quotes from dozens of verified logistics companies. Grow your business with sea, land, and air freight solutions.",
            "hero_btn_explore": "Explore Marketplace",
            "hero_btn_post": "Post an Ad Now",
            "stats_total_ads": "Total Ads",
            "stats_active_ads": "Active Ads",
            "stats_bids": "Total Bids",
            "stats_ports": "Global Ports",
            "how_it_works_title": "How Does It Work?",
            "how_it_works_desc": "We simplified complex logistics processes",
            "step1_title": "Define Your Cargo",
            "step1_desc": "Detail your needs. Get your ad published in 2 minutes.",
            "step2_title": "Compare Quotes",
            "step2_desc": "Evaluate transparent quotes from global companies.",
            "step3_title": "Manage the Process",
            "step3_desc": "Approve the agreement and track your cargo to its destination.",
            "why_title": "Why Pruva?",
            "why_desc": "Professional operational excellence",
            "feature1_title": "Speed and Efficiency",
            "feature1_desc": "Save time by accelerating quote processes by 80%.",
            "feature2_title": "Complete Security",
            "feature2_desc": "Verified company profiles and transparent evaluation system.",
            "feature3_title": "Real-time Tracking",
            "feature3_desc": "Track all stages step-by-step from your dashboard.",
            "feature4_title": "Global Reach",
            "feature4_desc": "Worldwide network of ports and strategic locations.",
            "feature5_title": "Seamless Communication",
            "feature5_desc": "Direct coordination with advanced messaging infrastructure.",
            "feature6_title": "Data Analytics",
            "feature6_desc": "Analyze and optimize your logistics costs.",
            "modes_title": "Logistics Solutions",
            "modes_desc": "Customized transport modes for every cargo",
            "mode1_title": "Sea Freight",
            "mode1_desc": "FCL/LCL, Container and Project Cargo solutions.",
            "mode1_badge": "Global Ports",
            "mode2_title": "Road Freight",
            "mode2_desc": "FTL/LTL and Full Truckload transportation.",
            "mode2_badge": "All Europe",
            "mode3_title": "Air Freight",
            "mode3_desc": "Express and Standard air cargo.",
            "mode3_badge": "Fastest Option",
            "eco_title": "Pruva Ecosystem",
            "eco_desc": "Not just a marketplace, your logistics solution partner",
            "academy_badge": "Education Portal",
            "academy_title": "Pruva Academy",
            "academy_desc": "Master the logistics world with our comprehensive curriculum consisting of 16 modules. Everything from freight forwarder operations to customs processes is here.",
            "academy_f1": "16 Comprehensive Modules",
            "academy_f2": "Professional Dictionary & Terms",
            "academy_f3": "Interactive Calculation Tools",
            "academy_btn": "Start Exploring",
            "ai_badge": "Artificial Intelligence",
            "ai_title": "Pruva AI",
            "ai_desc": "Smart assistant integrated into your company email, automatically analyzing quotes and negotiating the best price for you.",
            "ai_status": "Pricing Module Active",
            "ai_f1": "Automatic Email Scanning",
            "ai_f2": "Smart Quote Analysis",
            "ai_f3": "Automated Price Negotiation",
            "ai_btn": "Discover Now"
        }
    },
    zh: {
        "home": {
            "hero_badge": "土耳其的数字物流运营商",
            "hero_title": "将您的货物带向未来",
            "hero_desc": "从数十家经过验证的物流公司获得即时报价。利用海运、陆运和空运解决方案发展您的业务。",
            "hero_btn_explore": "探索市场",
            "hero_btn_post": "立即发布广告",
            "stats_total_ads": "总广告数",
            "stats_active_ads": "活跃广告",
            "stats_bids": "总出价数",
            "stats_ports": "全球港口",
            "how_it_works_title": "系统如何运作？",
            "how_it_works_desc": "我们简化了复杂的物流流程",
            "step1_title": "定义您的货物",
            "step1_desc": "详细说明您的需求。让您的广告在2分钟内发布。",
            "step2_title": "比较报价",
            "step2_desc": "评估来自全球公司的透明报价。",
            "step3_title": "管理流程",
            "step3_desc": "批准协议并跟踪您的货物直至目的地。",
            "why_title": "为什么选择 Pruva？",
            "why_desc": "专业的运营卓越",
            "feature1_title": "速度和效率",
            "feature1_desc": "通过将报价流程加快80%来节省时间。",
            "feature2_title": "完全安全",
            "feature2_desc": "经过验证的公司资料和透明的评估系统。",
            "feature3_title": "实时跟踪",
            "feature3_desc": "从您的仪表板逐步跟踪所有阶段。",
            "feature4_title": "全球影响力",
            "feature4_desc": "遍布全球的港口和战略地点网络。",
            "feature5_title": "无缝沟通",
            "feature5_desc": "通过高级消息传递基础架构进行直接协调。",
            "feature6_title": "数据分析",
            "feature6_desc": "分析和优化您的物流成本。",
            "modes_title": "物流解决方案",
            "modes_desc": "为每种货物定制运输模式",
            "mode1_title": "海运",
            "mode1_desc": "整箱/拼箱 (FCL/LCL)，集装箱和项目货物解决方案。",
            "mode1_badge": "全球港口",
            "mode2_title": "陆运",
            "mode2_desc": "整车/零担 (FTL/LTL) 和全卡车运输。",
            "mode2_badge": "全欧洲",
            "mode3_title": "空运",
            "mode3_desc": "快递和标准航空货运。",
            "mode3_badge": "最快选项",
            "eco_title": "Pruva 生态系统",
            "eco_desc": "不仅是市场，更是您的物流解决方案合作伙伴",
            "academy_badge": "教育门户",
            "academy_title": "Pruva 学院",
            "academy_desc": "通过包含16个模块的综合课程掌握物流世界。从货运代理操作到海关流程，应有尽有。",
            "academy_f1": "16 个综合模块",
            "academy_f2": "专业词典和术语",
            "academy_f3": "交互式计算工具",
            "academy_btn": "开始探索",
            "ai_badge": "人工智能",
            "ai_title": "Pruva AI",
            "ai_desc": "集成到您公司电子邮件中的智能助手，可自动分析报价并为您协商最佳价格。",
            "ai_status": "定价模块有效",
            "ai_f1": "自动电子邮件扫描",
            "ai_f2": "智能报价分析",
            "ai_f3": "自动价格谈判",
            "ai_btn": "立即发现"
        }
    },
    ru: {
        "home": {
            "hero_badge": "Цифровой логистический оператор Турции",
            "hero_title": "Перенесите свой груз в будущее",
            "hero_desc": "Мгновенно получайте расценки от десятков проверенных логистических компаний. Развивайте свой бизнес с помощью решений для морских, наземных и воздушных грузоперевозок.",
            "hero_btn_explore": "Изучить рынок",
            "hero_btn_post": "Опубликовать объявление",
            "stats_total_ads": "Всего объявлений",
            "stats_active_ads": "Активные объявления",
            "stats_bids": "Всего ставок",
            "stats_ports": "Глобальные порты",
            "how_it_works_title": "Как это работает?",
            "how_it_works_desc": "Мы упростили сложные логистические процессы",
            "step1_title": "Определите свой груз",
            "step1_desc": "Подробно опишите свои потребности. Ваше объявление будет опубликовано за 2 минуты.",
            "step2_title": "Сравните предложения",
            "step2_desc": "Оценивайте прозрачные предложения от международных компаний.",
            "step3_title": "Управляйте процессом",
            "step3_desc": "Одобрите соглашение и отслеживайте груз до места назначения.",
            "why_title": "Почему Pruva?",
            "why_desc": "Профессиональное операционное совершенство",
            "feature1_title": "Скорость и эффективность",
            "feature1_desc": "Экономьте время, ускоряя процессы котировок на 80%.",
            "feature2_title": "Полная безопасность",
            "feature2_desc": "Проверенные профили компаний и прозрачная система оценки.",
            "feature3_title": "Отслеживание в реальном времени",
            "feature3_desc": "Отслеживайте все этапы шаг за шагом со своей панели.",
            "feature4_title": "Глобальный охват",
            "feature4_desc": "Всемирная сеть портов и стратегических пунктов.",
            "feature5_title": "Бесперебойная связь",
            "feature5_desc": "Прямая координация с развитой инфраструктурой обмена сообщениями.",
            "feature6_title": "Аналитика данных",
            "feature6_desc": "Анализируйте и оптимизируйте свои логистические затраты.",
            "modes_title": "Логистические решения",
            "modes_desc": "Индивидуальные виды транспорта для каждого груза",
            "mode1_title": "Морские перевозки",
            "mode1_desc": "Решения FCL/LCL, контейнерные и проектные грузы.",
            "mode1_badge": "Глобальные порты",
            "mode2_title": "Автомобильные перевозки",
            "mode2_desc": "FTL/LTL и полногрузные автомобильные перевозки.",
            "mode2_badge": "Вся Европа",
            "mode3_title": "Авиаперевозки",
            "mode3_desc": "Экспресс- и стандартные авиаперевозки.",
            "mode3_badge": "Самый быстрый вариант",
            "eco_title": "Экосистема Pruva",
            "eco_desc": "Не просто рынок, а ваш партнер по логистическим решениям",
            "academy_badge": "Образовательный портал",
            "academy_title": "Академия Pruva",
            "academy_desc": "Освойте мир логистики с помощью нашей комплексной учебной программы, состоящей из 16 модулей. Здесь есть все, от операций экспедитора до таможенных процессов.",
            "academy_f1": "16 комплексных модулей",
            "academy_f2": "Профессиональный словарь и термины",
            "academy_f3": "Интерактивные инструменты расчета",
            "academy_btn": "Начать изучение",
            "ai_badge": "Искусственный интеллект",
            "ai_title": "Pruva AI",
            "ai_desc": "Умный помощник, интегрированный в вашу корпоративную почту, автоматически анализирующий предложения и договаривающийся о лучшей цене для вас.",
            "ai_status": "Модуль ценообразования активен",
            "ai_f1": "Автоматическое сканирование электронной почты",
            "ai_f2": "Умный анализ предложений",
            "ai_f3": "Автоматические переговоры о цене",
            "ai_btn": "Узнать сейчас"
        }
    },
    es: {
        "home": {
            "hero_badge": "Operador Logístico Digital de Turquía",
            "hero_title": "Lleve su carga hacia el futuro",
            "hero_desc": "Obtenga cotizaciones instantáneas de docenas de empresas de logística verificadas. Haga crecer su negocio con soluciones de transporte marítimo, terrestre y aéreo.",
            "hero_btn_explore": "Explorar el mercado",
            "hero_btn_post": "Publicar un anuncio",
            "stats_total_ads": "Total de anuncios",
            "stats_active_ads": "Anuncios activos",
            "stats_bids": "Total de ofertas",
            "stats_ports": "Puertos globales",
            "how_it_works_title": "¿Cómo funciona?",
            "how_it_works_desc": "Simplificamos los procesos logísticos complejos",
            "step1_title": "Defina su carga",
            "step1_desc": "Detalle sus necesidades. Publique su anuncio en 2 minutos.",
            "step2_title": "Compare cotizaciones",
            "step2_desc": "Evalúe las cotizaciones transparentes de empresas globales.",
            "step3_title": "Administre el proceso",
            "step3_desc": "Apruebe el acuerdo y rastree su carga hasta su destino.",
            "why_title": "¿Por qué Pruva?",
            "why_desc": "Excelencia operativa profesional",
            "feature1_title": "Velocidad y eficiencia",
            "feature1_desc": "Ahorre tiempo acelerando los procesos de cotización en un 80%.",
            "feature2_title": "Seguridad completa",
            "feature2_desc": "Perfiles de empresas verificados y sistema de evaluación transparente.",
            "feature3_title": "Seguimiento en tiempo real",
            "feature3_desc": "Rastree todas las etapas paso a paso desde su panel de control.",
            "feature4_title": "Alcance global",
            "feature4_desc": "Red mundial de puertos y ubicaciones estratégicas.",
            "feature5_title": "Comunicación perfecta",
            "feature5_desc": "Coordinación directa con infraestructura de mensajería avanzada.",
            "feature6_title": "Análisis de datos",
            "feature6_desc": "Analice y optimice sus costos logísticos.",
            "modes_title": "Soluciones logísticas",
            "modes_desc": "Modos de transporte personalizados para cada carga",
            "mode1_title": "Flete marítimo",
            "mode1_desc": "FCL/LCL, Soluciones de contenedores y carga de proyectos.",
            "mode1_badge": "Puertos globales",
            "mode2_title": "Flete terrestre",
            "mode2_desc": "FTL/LTL y transporte de camión completo.",
            "mode2_badge": "Toda Europa",
            "mode3_title": "Flete aéreo",
            "mode3_desc": "Carga aérea estándar y urgente.",
            "mode3_badge": "Opción más rápida",
            "eco_title": "Ecosistema Pruva",
            "eco_desc": "No solo un mercado, su socio de soluciones logísticas",
            "academy_badge": "Portal educativo",
            "academy_title": "Academia Pruva",
            "academy_desc": "Domine el mundo de la logística con nuestro completo plan de estudios de 16 módulos. Todo, desde las operaciones del transitario hasta los procesos aduaneros, está aquí.",
            "academy_f1": "16 módulos completos",
            "academy_f2": "Diccionario profesional y términos",
            "academy_f3": "Herramientas de cálculo interactivas",
            "academy_btn": "Empezar a explorar",
            "ai_badge": "Inteligencia artificial",
            "ai_title": "Pruva AI",
            "ai_desc": "Asistente inteligente integrado en el correo electrónico de su empresa, analizando automáticamente las cotizaciones y negociando el mejor precio para usted.",
            "ai_status": "Módulo de precios activo",
            "ai_f1": "Escaneo automático de correo electrónico",
            "ai_f2": "Análisis inteligente de cotizaciones",
            "ai_f3": "Negociación automática de precios",
            "ai_btn": "Descubrir ahora"
        }
    }
};

const langs = ['tr', 'en', 'zh', 'ru', 'es'];
langs.forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    let current = {};
    if (fs.existsSync(filePath)) {
        current = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    }
    current.home = homeTranslations[lang].home;
    fs.writeFileSync(filePath, JSON.stringify(current, null, 2));
    console.log(`Updated ${lang}.json with home`);
});
